import {Raleway} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/footer";
import { Toaster } from "react-hot-toast";


const RalewayFont=Raleway({
   weight:["200","300","500","600","700","900"]
})

export const metadata = {
  title: "Driftly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${RalewayFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="sticky top-0 z-50 bg-white">
          <Navbar></Navbar>
        </header>
        <main>
          {children}
        </main>
        <Footer></Footer>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
