import { Geist, Geist_Mono, Raleway, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";


const RalewayFont=Raleway({
   weight:["200","300","500","600","700","900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${RalewayFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Navbar></Navbar>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
